# Generated by Django 3.2.8 on 2022-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_certificate',
            field=models.ImageField(upload_to='pics/images', verbose_name='Hotel_Certificate'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_photo',
            field=models.ImageField(upload_to='pics/images', verbose_name='Hotel_Photo'),
        ),
    ]
