# Generated by Django 3.2.8 on 2022-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20220304_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_certificate',
            field=models.ImageField(upload_to='pics/images'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_photo',
            field=models.ImageField(upload_to='pics/images'),
        ),
    ]
