# Generated by Django 3.2.8 on 2022-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_auto_20220304_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_certificate',
            field=models.ImageField(db_column='hotel_certificate', upload_to='images', verbose_name='Hotel_Certificate'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_photo',
            field=models.ImageField(db_column='hotel_photo', upload_to='images', verbose_name='Hotel_Photo'),
        ),
    ]
