# Generated by Django 3.2.8 on 2022-03-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_auto_20220304_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoteldashboardModel',
            fields=[
                ('hoteldashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(db_column='room_type', max_length=50, verbose_name='Room_type')),
                ('room_size', models.CharField(db_column='room_size', max_length=50, verbose_name='Room_size')),
                ('check_in', models.CharField(db_column='check_in', max_length=50, verbose_name='Check_in')),
                ('check_out', models.CharField(db_column='check_out', max_length=50, verbose_name='Check_out')),
                ('price', models.CharField(blank=True, db_column='price', max_length=100, null=True, verbose_name='Price')),
                ('description', models.CharField(db_column='description', max_length=100, verbose_name='Description')),
                ('hotel_policies', models.CharField(db_column='hotel_policies', max_length=100, verbose_name='Hotel_policies')),
                ('room_photo', models.ImageField(db_column='room_photo', upload_to='room/images/', verbose_name='Room_Photo')),
            ],
            options={
                'db_table': 'hotel_dashboard',
            },
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_certificate',
            field=models.ImageField(db_column='hotel_certificate', upload_to='hotel/certificate/', verbose_name='Hotel_Certificate'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_photo',
            field=models.ImageField(db_column='hotel_photo', upload_to='hotel/images/', verbose_name='Hotel_Photo'),
        ),
    ]
