# Generated by Django 3.2.8 on 2022-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_auto_20220309_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldashboardmodel',
            old_name='hoteldashboard_id',
            new_name='room_id',
        ),
        migrations.AlterField(
            model_name='hoteldashboardmodel',
            name='room_photo',
            field=models.ImageField(db_column='room_photo', upload_to='room/images/', verbose_name='Room_photo'),
        ),
    ]
