# Generated by Django 3.2.8 on 2022-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_auto_20220309_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldashboardmodel',
            name='check_in',
            field=models.TimeField(db_column='check_in', max_length=50, verbose_name='Check_in'),
        ),
        migrations.AlterField(
            model_name='hoteldashboardmodel',
            name='check_out',
            field=models.TimeField(db_column='check_out', max_length=50, verbose_name='Check_out'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_email',
            field=models.EmailField(blank=True, db_column='hotel_email', max_length=100, null=True, verbose_name='Hotel_Email'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_phone',
            field=models.BigIntegerField(db_column='hotel_phone', verbose_name='Hotel_Phone'),
        ),
    ]
