# Generated by Django 3.2.8 on 2022-03-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('fb_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(db_column='rating', max_length=50, verbose_name='Rating')),
                ('hotel_id', models.CharField(db_column='hotel_id', max_length=50, null=True, verbose_name='Hotel_id')),
                ('comments', models.TextField(db_column='comments', max_length=50, verbose_name='Comments')),
                ('agency_id', models.CharField(db_column='agency_id', max_length=50, verbose_name='Agency_id')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
    ]
