# Generated by Django 3.2.8 on 2022-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_userfeedback_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(db_column='email', max_length=50, null=True, verbose_name='Email'),
        ),
    ]
