# Generated by Django 3.2.8 on 2022-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelModel',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(db_column='agency_name', max_length=50, verbose_name='Agency_Name')),
                ('agency_pan_number', models.CharField(db_column='agency_pan_number', max_length=50, verbose_name='Agency_Pan_number')),
                ('agency_addres', models.CharField(db_column='agency_Addres', max_length=50, verbose_name='Agency_Addres')),
                ('agency_phone', models.CharField(db_column='agency_phone', max_length=50, verbose_name='Agency_Phone')),
                ('agency_email', models.CharField(blank=True, db_column='agency_email', max_length=100, null=True, verbose_name='Agency_Email')),
                ('agency_pwd', models.CharField(db_column='agency_pwd', max_length=100, verbose_name='Agency_Password')),
                ('agency_photo', models.ImageField(db_column='agency_photo', upload_to='travel/images/', verbose_name='Agency_Photo')),
                ('iata_certificate', models.ImageField(db_column='iata_certificate', upload_to='travel/certificate/', verbose_name='IATA_Certificate')),
            ],
            options={
                'db_table': 'travel_details',
            },
        ),
    ]
