# Generated by Django 3.2.8 on 2022-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardashboardModel',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_type', models.CharField(db_column='car_type', max_length=50, verbose_name='Car_type')),
                ('car_model', models.CharField(db_column='car_model', max_length=50, verbose_name='Car_model')),
                ('car_no', models.CharField(db_column='car_no', max_length=50, verbose_name='Car_no')),
                ('select_car', models.CharField(db_column='select_car', max_length=50, verbose_name='Select_car')),
                ('price', models.CharField(blank=True, db_column='price', max_length=100, null=True, verbose_name='Price')),
                ('car_photo', models.ImageField(db_column='car_photo', upload_to='room/images/', verbose_name='Car_photo')),
            ],
            options={
                'db_table': 'car_dashboard',
            },
        ),
    ]
