# Generated by Django 3.2.8 on 2022-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_cardashboardmodel_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdashboardmodel',
            name='flight_photo',
            field=models.ImageField(db_column='flight_photo', upload_to='flight/images/', verbose_name='Flight_photo'),
        ),
    ]
