# Generated by Django 3.2.8 on 2022-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_alter_flightdashboardmodel_flight_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisesdashboardmodel',
            name='cruises_photo',
            field=models.ImageField(db_column='cruises_photo', upload_to='cruises/images/', verbose_name='Cruises_photo'),
        ),
    ]
