# Generated by Django 3.2.8 on 2022-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_auto_20220315_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmodel',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelmodel',
            name='agency_phone',
            field=models.BigIntegerField(db_column='agency_phone', verbose_name='Agency_Phone'),
        ),
    ]
