# Generated by Django 3.2.8 on 2022-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_auto_20220318_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardashboardmodel',
            name='agency_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cruisesdashboardmodel',
            name='agency_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdashboardmodel',
            name='agency_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
